//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './NotFound.module.scss';

class NotFound extends React.Component{

	render(){
		return (
			<div className={styles.container}>
				<h1>404 - Not Found</h1>
				<p>We couldn't find this page</p>
			</div>
		);
	}

}
export default NotFound;
