//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './List.module.scss';

import { FaExpandArrowsAlt, FaCompressArrowsAlt } from 'react-icons/fa';

class List extends React.Component{
    constructor(props){
        super(props);
        this.handleClickDiv = this.handleClickDiv.bind(this);
        this.state = {
            opened: false
        };
        this.close = this.close.bind(this);
    }
    handleClickDiv(e){
        this.props.closeLists();
        if(!this.state.opened || e.target.closest('.'+styles['icon-container'])){
            this.setState({
                opened: !this.state.opened
            });
        }
    }
    close(){
        this.setState({
            opened: false
        });
    }
	render(){
		return (
            <div className={styles['list-container']+' '+(this.state.opened && styles['opened'])} onClick={this.handleClickDiv}>
                <div className={styles['icon-container']}>
                    {this.state.opened ? <FaCompressArrowsAlt /> : <FaExpandArrowsAlt />}
                </div>
                <strong>#{this.props.id} - {this.props.title}</strong>
                <span>Due date: {this.props.due_date ? new Date(this.props.due_date).toDateString() : '<never>'}</span>
                <span>Items: {`${this.props.items_done}/${this.props.items_count}`}</span>
                {
                    this.props.description &&
                    <p>Description: {this.props.description.substr(0,120)}{this.props.description.length > 120 && '...'}</p>
                }
                {(
                    this.state.opened &&
                    <div>
                        <h1>opened</h1>

                    </div>
                )}
            </div>
        );
	}

}
export default List;
