//@author: beto0607
//generated by create_container

import React from 'react';
//import styles from './ListItem.module.scss';

class ListItem extends React.Component{

	// constructor(props){
	// 	super(props);
	// }

	render(){
		return (<h1>ListItem</h1>);
	}

}
export default ListItem;
