//@author: beto0607
//generated by create_container

import React, { useState } from "react";
import styles from "./ListItem.module.scss";

import { FaCheckCircle } from "react-icons/fa";
import {
    getItemResolveURL,
    getItemUnsolveURL,
    doPATCH
} from "../../utils/utils";
import ItemDelete from "./ItemDelete";

const ListItem = ({ id, attributes, showErrors }) => {
    const { title, status } = attributes;
    const [statusState, setStatus] = useState(status);
    const handleItemClick = () => {
        doPATCH(
            statusState === "DONE"
                ? getItemUnsolveURL(id)
                : getItemResolveURL(id),
            null,
            ({ data }) => {
                setStatus(data.attributes.status);
            },
            errors => {
                showErrors(errors);
            }
        );
    };
    return (
        <li
            className={
                styles["container"] + " " + styles[statusState.toLowerCase()]
            }
            onClick={handleItemClick}>
            <div className={styles["status-container"]}>
                {statusState === "DONE" && <FaCheckCircle />}
            </div>
            <span>{title}</span>
            <ItemDelete id={id} showErrors={showErrors} onDeleteItem={console.log} />
        </li>
    );
};

export default ListItem;
