//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './Footer.module.scss';

class Footer extends React.Component{

	constructor(props){
		super(props);
	}

	render(){
		return (<h1>Footer</h1>);
	}

}
export default Footer;
