//@author: beto0607
//generated by create_container

import React from "react";
import styles from "./Layout.module.scss";

class Header extends React.Component {
  render() {
    return (
      <header className={styles.header}>
        {this.props.children || [
          <img className={styles.logo} key="logo_image" alt="Logo"/>,
          <nav key="nav_bar">Bananas</nav>
        ]}
      </header>
    );
  }
}
export default Header;
