//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './Layout.module.scss';
import Header from './Header';

class Layout extends React.Component{
	render(){
		return (
            <div className={styles.container}>
                <Header>
                    {this.props.header || null}
                </Header>
                <main className={styles.main}>
                    {
                        this.props.main ||
                        this.props.children || 
                        null
                    }
                </main>
                <footer>
                    {
                        this.props.footer || null
                    }
                </footer>
            </div>
        );
	}

}
export default Layout;
