//@author: beto0607
//generated by create_container

import React from "react";
import styles from "./Layout.module.scss";
import Header from "./Header";
import Footer from "./Footer";
class Layout extends React.Component {
    render() {
        return (
            <div className={styles.container}>
                <Header title="Layout">{this.props.header || null}</Header>
                <main className={styles.main}>
                    {this.props.main || this.props.children || null}
                </main>
                <Footer />
            </div>
        );
    }
}
export default Layout;
