//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './LoadingSpinner.module.scss';
import { fadeIn } from 'react-animations'

class LoadingSpinner extends React.Component{
	render(){
		return (
            <div className={styles['container']}>
                <div className={styles['loading-container']}>
                    Loading
                </div>
            </div>
        );
	}
}
export default LoadingSpinner;
