//@author: beto0607
//generated by create_container

import React from "react";
import styles from "./LoadingSpinner.module.scss";
import Flip from "react-reveal/Flip";

const LoadingSpinner = () => (
    <Flip left>
        <div className={styles["container"]}>
            <div className={styles["loading-container"]}>Loading</div>
        </div>
    </Flip>
);
export default LoadingSpinner;
