//@author: beto0607
//generated by create_container

import React, { useState } from "react";
import styles from "./ListNew.module.scss";
import { doPOST, getUserListsURL, getUserId } from "../../utils/utils";

import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

const handleSubmit = (event, due_date, { listAdded, showErrors }) => {
    event.preventDefault();
    let formData = new FormData(event.target);
    doPOST(
        getUserListsURL(getUserId()),
        {
            list: {
                title: formData.get("title"),
                due_date: due_date,
                description: formData.get("description")
            }
        },
        listAdded,
        showErrors
    );
};
const ListNew = ({ listAdded, showErrors, close }) => {
    const [due_date, setDueDate] = useState(new Date());
    return (
        <div className={styles["add-list-container"]}>
            <form
                onSubmit={event =>
                    handleSubmit(event, due_date, { listAdded, showErrors })
                }>
                <div className={styles["input-container"]}>
                    <h2>New List</h2>
                </div>
                <hr />
                <div className={styles["input-container"]}>
                    <label htmlFor="title">Title:</label>
                    <input type="text" name="title" />
                </div>
                <div className={styles["input-container"]}>
                    <label htmlFor="title">Due date:</label>
                    <DatePicker
                        selected={due_date}
                        onChange={date => setDueDate(date)}
                        showTimeSelect
                        dateFormat="Pp"
                    />
                </div>
                <div className={styles["input-container"]}>
                    <label htmlFor="description">Description:</label>
                    <textarea name="description" />
                </div>
                <input type="submit" value="Create" />
                <button onClick={close} type="button">
                    Cancel
                </button>
            </form>
        </div>
    );
};

export default ListNew;
