//@author: beto0607
//generated by create_container

import React from "react";
import styles from "./ListNew.module.scss";
import { doPOST, getUserListsURL, getUserId } from "../../utils/utils";

class ListNew extends React.Component {
    constructor(props) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);
        this.handleListNewSuccess = this.handleListNewSuccess.bind(this);
        this.handleListNewError = this.handleListNewError.bind(this);
    }
    handleListNewSuccess(data) {
        this.props.listAdded(data);
    }
    handleListNewError(err) {
        console.log(err);
        this.props.showErrors(err);
    }
    handleSubmit(e) {
        e.preventDefault();
        let formData = new FormData(e.target);
        const title = formData.get("title");
        let data = {
            title: title
        };
        const due_date = formData.get("due_date");
        if (due_date) {
            data["due_date"] = due_date;
        }
        const description = formData.get("description");
        if (description) {
            data["due_date"] = description;
        }
        doPOST(
            getUserListsURL(getUserId()),
            { list: data },
            this.handleListNewSuccess,
            this.handleListNewError
        );
    }
    render() {
        return (
            <div className={styles["add-list-container"]}>
                <form onSubmit={this.handleSubmit}>
                    <div className={styles["input-container"]}>
                        <h2>New List</h2>
                    </div>
                    <hr />
                    <div className={styles["input-container"]}>
                        <label htmlFor="title">Title:</label>
                        <input type="text" name="title" />
                    </div>
                    <div className={styles["input-container"]}>
                        <label htmlFor="title">Due date:</label>
                        <input
                            type="datetime-local"
                            name="due_date"
                            defaultValue={new Date().toISOString().slice(0, -1)}
                        />
                    </div>
                    <div className={styles["input-container"]}>
                        <label htmlFor="description">Description:</label>
                        <textarea name="description" />
                    </div>
                    <input type="submit" value="Create" />
                    <button onClick={this.props.close}>Cancel</button>
                </form>
            </div>
        );
    }
}
export default ListNew;
