//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './Home.module.scss';

class Home extends React.Component{

	render(){
		return (<h1>Home</h1>);
	}

}
export default Home;
