//@author: beto0607
//generated by create_container

import React from "react";
import styles from "./Register.module.scss";

class Register extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            url: this.props.base_url + "users"
        };
        this.handleSubmit = this.handleSubmit.bind(this);
    }
    handleSubmit(e) {
        e.preventDefault();
        const data = new FormData(e.target);
        const json_data = {
            user: {
                email: data.get("email"),
                username: data.get("username"),
                password: data.get("password"),
                password_confirmation: data.get("password_confirm")
            }
        };
        fetch(this.state.url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(json_data)
        })
            .then(function(response) {
                console.log(response);
                return response.json();
            })
            .then(data => {
                localStorage.setItem("token", data.token);
                localStorage.setItem("username", data.username);
                localStorage.setItem("token_expires", data.exp);
                if (this.props.success) this.props.success();
            })
            .catch(err => {
                if (this.props.error) {
                    if (err.errors) {
                        this.props.error(err.errors.join(" "));
                    } else {
                        this.props.error("An unknown error has occurred.");
                        console.log(err);
                    }
                }
            });
    }
    render() {
        return (
            <div>
                <form onSubmit={this.handleSubmit}>
                    <div className={styles["input-container"]}>
                        <label htmlFor="email">Email:</label>
                        <input type="email" name="email" />
                    </div>
                    <div className={styles["input-container"]}>
                        <label htmlFor="username">Username:</label>
                        <input
                            type="text"
                            name="username"
                            minLength="6"
                            maxLength="20"
                        />
                    </div>
                    <div className={styles["input-container"]}>
                        <label htmlFor="password">Password:</label>
                        <input
                            type="password"
                            name="password"
                            minLength="6"
                            maxLength="20"
                        />
                    </div>
                    <div className={styles["input-container"]}>
                        <label htmlFor="password_confirm">
                            Password confirm:
                        </label>
                        <input
                            type="password"
                            name="password_confirm"
                            minLength="6"
                            maxLength="20"
                        />
                    </div>
                    <input type="submit" value="Register!" />
                </form>
            </div>
        );
    }
}
export default Register;
