//@author: beto0607
//generated by create_container
/**
 * Notification sysmtem component.
 * It takes all the messages in an array prop called messages.
 * each message must have a type(good or error), a title and a detail
 */
import React from "react";
import styles from "./NotificationSystem.module.scss";

const Message = props => (
  <div className={styles[props.type + "-messages"]}>
    <strong>{props.title} </strong>
    <span>{props.detail}</span>
  </div>
);

class NotificationSystem extends React.Component {
  constructor(props) {
    super(props);
    this.messagesCount = 0;
  }

  render() {
    return (
      <div className={styles["container"]}>
        {this.props.messages.map((e) => {
          this.messagesCount++;
          return <Message {...e} key={"message#" + this.messagesCount} />;
        })}
      </div>
    );
  }
}
export default NotificationSystem;
