//@author: beto0607
//generated by create_container

import React from 'react';
import styles from './Dashboard.module.scss';

class Dashboard extends React.Component{

	render(){
		return (<h1>Dashboard</h1>);
	}

}
export default Dashboard;
